export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_BODY = 'CHANGE_BODY';

export const FETCH_ADD_POSTS = 'FETCH_ADD_POSTS';
export const FETCH_ADD_POSTS_SUCCESS = 'FETCH_ADD_POSTS_SUCCESS';
export const FETCH_ADD_POSTS_ERROR = 'FETCH_ADD_POSTS_ERROR';