export const CHANGE_INPUTS = 'CHANGE_INPUTS';

export const SWITCH_EDIT_SHOW = 'SWITCH_EDIT_SHOW';

export const FETCH_ADD_POSTS = 'FETCH_ADD_POSTS';
export const FETCH_ADD_POSTS_SUCCESS = 'FETCH_ADD_POSTS_SUCCESS';
export const FETCH_ADD_POSTS_ERROR = 'FETCH_ADD_POSTS_ERROR';